### ISSUE TITLE
CLI truncates stdout output

### ISSUE THREAD

**Issue by rrthomas** [Amourspirit/node-base64-string#20]
Currently, the CLI script explicitly calls process.exit(0) on successful termination. This prevents stdout from draining, and when using output to stdout, the output can be truncated.

Since Node will return an exit code of 0 on non-error termination in any case, the simplest fix is to remove this process.exit(0) call from the end of the script. When Node shuts down it will first drain stdout.

PR #19 fixes this bug, and I have made a temporary [npmjs.com release](https://www.npmjs.com/package/@sc3d/base64-string) of my fork.

**Comment by Amourspirit** [comment]
Thanks, change are in the published [1.1.3](https://www.npmjs.com/package/base64-string) version.

**Comment by rrthomas** [comment]
Many thanks for the quick update.
